project:
  type: website

website:
  title: "Chemical and Thermal Processes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: basics/
        text: 'Basics'
      - text: 'Balances'
        menu:
        - href: balances/general
          text: 'General'
        - href: balances/material
          text: 'Material'
        - href: balances/energy
          text: 'Energy'
        - href: balances/entropy
          text: 'Entropy'
        - href: balances/exergy
          text: 'exergy'
      - href: phase/
        text: 'Phase Equilibria'
      - href: react/
        text: 'Reactors'
      - href: appx/
        text: 'Appendices'

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

execute:
  freeze: auto

